### PR TITLE
Feature/copy feature array to element array

### PR DESCRIPTION
**Pull request by VKUDRI**
Altered error conditions so instances with less Feature IDs than the total available are still valid

### CODE REVIEW

**Review by imikejackson — CHANGES_REQUESTED** [review]
I think we would need to get a "Fill value" from the user for the unused indices in the feature level array. We could just assume zero but that has caused problems in the past.

**Comment by VKUDRI** [comment]
> I think we would need to get a "Fill value" from the user for the unused indices in the feature level array. We could just assume zero but that has caused problems in the past.

Would there be unused indices? If I have feature ids  1-7 and then my feature array has instances of 1,3,4,5, and 6 all the indices in the created element array will have valid ids, it just will not use all the possible ids.

**Comment by imikejackson** [comment]
Sounds good then.

**Review by imikejackson — APPROVED** [review]

**Comment by VKUDRI** [comment]
Changed error message, converted to warning

**Comment by imikejackson** [comment]
These fixes were incorporated into another PR. Closing.

**Pull request closed without merging**
