### PR TITLE
Fix type of cast, check for valid pointers before using.

### PR DESCRIPTION
**Pull request by imikejackson**
SVPipelineView needs sanity checks on pointers before using them because the source
of the variable could return null pointers.

Signed-off-by: Michael Jackson <mike.jackson@bluequartz.net>

### CODE REVIEW

**Comment by imikejackson** [comment]
Not sure we really need that big output block to StdOut.

**Review by mmarineBlueQuartz — APPROVED** [review]
This looks good.

**Review by mmarineBlueQuartz — CHANGES_REQUESTED** [review]
Upon further inspection, lines 383 and 388 also have the same nullptr error.  PipelineModel does not clear items when a filter is removed from the pipeline, and thus model->filter(childIndex) will return nullptr for legitimate indices for the pipeline.  The initial check if the PipelineModel is null is valid as there is no guarantee that the view's QAbstractItemModel* has to be castable to PipelineModel* other than that a failure to do so should not happen.  The same was assumed for `model->filter(childIndex);` not returning null in multiple places.

**Comment by imikejackson** [comment]
This PR has been supplanted by #304

**Pull request closed without merging**
