### PR TITLE
Only copy Public filter docs into the build folder

### PR DESCRIPTION
**Pull request by imikejackson**
All the other repositories also have this same branch.

### CODE REVIEW

**Review by JDuffeyBQ — COMMENTED** [review]
We'll need to add the superclass macro to ITKImageProcessing as well. The rest of the Python tests pass on my machine.

**Comment by imikejackson** [comment]
I'll run another full clean build + testing on that and report back.

**Comment by imikejackson** [comment]
If we go with a pure virtual for getNameOfClass() does that mess up the Pybind11 bindings?

**Comment by JDuffeyBQ** [comment]
I don't think so since execute() is also pure virtual, and that hasn't caused any issues.

**Comment by JDuffeyBQ** [comment]
I've compiled with getNameOfClass() as pure virtual and all the tests passed.

**Pull request closed without merging**
