### PR TITLE
Add transform

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by thewtex** [comment]
Thanks, Mike.

**Comment by imikejackson** [comment]
Something blew up on the build bots when I merged. I'm taking a look at it now.

**Comment by imikejackson** [comment]
There is also this warning that *might* be related to the differences between ITK 4 and 5?

uded from /Users/mjackson/DREAM3D-Dev/DREAM3D/ExternalProjects/SIMPL/Source/SIMPLib/ITK/Testing/Cxx/itkDream3DTransformContainerToTransformTest.cpp:34:
/Users/mjackson/DREAM3D-Dev/DREAM3D/ExternalProjects/SIMPL/Source/SIMPLib/ITK/itkDream3DTransformContainerToTransform.h:57:16: warning: 'itk::Dream3DTransformContainerToTransform<itk::AffineTransform<float, 3> >::SetInput' hides overloaded virtual function [-Woverloaded-virtual]
  virtual void SetInput(::TransformContainer::Pointer transformContainer);
               ^
/Users/mjackson/DREAM3D-Dev/DREAM3D/ExternalProjects/SIMPL/Source/SIMPLib/ITK/Testing/Cxx/itkDream3DTransformContainerToTransformTest.cpp:53:5: note: in instantiation of template class 'itk::Dream3DTransformContainerToTransform<itk::AffineTransform<float, 3> >' requested here
    FilterType::Pointer filter = FilterType::New();
    ^
/Users/Shared/DREAM3D_SDK/superbuild/ITK/Source/ITK/Modules/Core/Common/include/itkProcessObject.h:524:16: note: hidden overloaded virtual function 'itk::ProcessObject::SetInput' declared here: different number of parameters (2 vs 1)
  virtual void SetInput(const DataObjectIdentifierType & key, DataObject *input);

**Comment by thewtex** [comment]
This patch should address that warning:  https://github.com/BlueQuartzSoftware/SIMPL/pull/232

**Pull request merged**
