### PR TITLE
missing declaration on Windows platform

### PR DESCRIPTION
**Pull request by v7t**
fix compilation errors  …
- QRegularExpressionValidator and QRegularExpression not defined in "datacontainercreationwidget.cpp"
--> #include "filterparameterwidgetutils.hpp"

- undefined QButton group in "FileListInfoWidget.cpp"
--> #include <QtWidgets/QButtonGroup>

### CODE REVIEW

**Comment by imikejackson** [comment]
Which version of Visual Studio are you using? The code currently compiles with VS2015 and VS2017  in 64 bit mode.

**Comment by v7t** [comment]
Visual Studio 2015 64 bits.

Interestingly if I comment all the #include "FilterParameterWidgetUtils.hpp" in the SVWidgetsLib project and build it, there is only one error which shows up like this:

1>------ Build started: Project: SVWidgetsLib, Configuration: Release x64 ------
1>  DataContainerCreationWidget.cpp
1>D:\MDF_DataAnalyticsTeam\Vincent\SIMPL\Source\SVWidgetsLib\FilterParameterWidgets\DataContainerCreationWidget.cpp(83): error C2061: syntax error: identifier 'QRegularExpressionValidator'
1>D:\MDF_DataAnalyticsTeam\Vincent\SIMPL\Source\SVWidgetsLib\FilterParameterWidgets\DataContainerCreationWidget.cpp(83): error C2143: syntax error: missing ';' before ')'
1>D:\MDF_DataAnalyticsTeam\Vincent\SIMPL\Source\SVWidgetsLib\FilterParameterWidgets\DataContainerCreationWidget.cpp(83): error C2059: syntax error: ')'
========== Build: 0 succeeded, 1 failed, 4 up-to-date, 0 skipped ==========

All the other widgets get the definition from somewhere else.

**Comment by imikejackson** [comment]
What version of Qt are you using? I'm trying to track down why we are not seeing the compile error. Once I get settled on the inherent difference I can merge the code.

**Comment by v7t** [comment]
Qt 5.11.1 and that might be the main difference because I am sure I compiled this project without problem before

**Comment by imikejackson** [comment]
We don't have any build bots that are using Qt 5.11.1 so I believe that you are correct. I'll get this merged into develop since we would hit this fairly soon. Thanks

**Pull request merged**
